#!/bin/bash
DESTDIR=~/Dokumente

a2x -f chunked yaVDR_doc.txt --xsl-file=ya_chunked.xsl --stylesheet=ya_docbook-xsl.css -a toclevels=8 --destination-dir=$DESTDIR -L --icons --xsltproc-opts="--param local.l10n.xml document\(\'custom-chapter.xml\'\)" --xsltproc-opts "--stringparam toc.section.depth 8" 
# read -p "Done. Press [ENTER] to exit..."
